config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users
  resources :tweets
  resources :likes
  
  #root 'users#index'
  #root 'tweets#index'
  root 'top#main'
    
  post 'top/login'
    
  get  'top/main'
  get  'top/logout'
  get  'top/error'
  get 'top/rock'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    
    #has_many :likes
    has_many :likes, dependent: :destroy
    has_many :like_users, through: :likes, source: :user
    
    def like(user)
        likes.create(user_id: user.id)
    end

    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end

    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    #has_many :tweets
    has_many :tweets, dependent: :destroy
    validates :uid, presence: true, uniqueness: true
    #validates :pass, presence: true
    validates :password, presence: true, confirmation: true
    attr_accessor :password, :password_confirmation
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
    
    
    
    #has_many :likes
    has_many :likes, dependent: :destroy
    has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_user
            if session[:login_uid]
            User.find_by(uid: session[:login_uid])
            end
        end
        helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
       tweet = Tweet.find(params[:tweet_id])
       #user = User.find_by(uid: session[:login_uid])
       #user.like_tweets << tweet
       unless tweet.liked?(current_user)
        tweet.like(current_user)
       end
       
       #redirect_to controller: :top, action: :main
       redirect_to root_path
    end
    
    def destroy
       tweet = Tweet.find(params[:id])
       #user = User.find_by(uid: session[:login_uid])
       #tweet.likes.find_by(user_id: user.id).destroy
       if tweet.liked?(current_user)
        tweet.unlike(current_user)
       end
       #redirect_to controller: :top, action: :main
       redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        @tweets = Tweet.all
        @likes = Like.all
        @users = User.all
        #if session[:login_uid]
        if current_user
            render "main"
        
        else
            render "login"
        end
    end
    #def login

        #if User.find_by(uid: params[:uid],pass: params[:pass])
            #session[:login_uid] = params[:uid]
            #redirect_to root_path
        
        #else
            #render 'error'
        #end
    #end
    
    def login
        user = User.find_by(uid: params[:uid])

        if user && BCrypt::Password.new(user.pass) == params[:pass]
            
            session[:login_uid] = params[:uid]
            redirect_to root_path
        
        else
            render 'error'
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
    
    def rock
        @users = User.all
       render "users/rock" 
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.all
  end
  
  def new 
    @tweets = Tweet.new
  end
  
  def create
    #@users = User.all
    
    #id = User.find_by(uid: session[:login_uid])
    
    
    #@tweets = Tweet.new(message: params[:tweet][:message],user_id: id.id)
    @tweets = Tweet.new(message: params[:tweet][:message],user_id: current_user.id)
    if @tweets.save
        redirect_to '/'
    else
        render 'new'
    end
  end
  
  def destroy
    b = Tweet.find(params[:id])
    b.destroy
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def new
        @users = User.new 
    end
    
    def create
        
        #@users =  User.new(uid: params[:user][:uid], pass: BCrypt::Password.create(params[:user][:pass]))
        @users = User.new(uid: params[:user][:uid], password: params[:user][:password], password_confirmation:params[:user][:password_confirmation])
        
        
        #@users = User.new(uid: params[:user][:uid], pass: params[:user][:pass])
        if @users.save
            redirect_to '/'
        else
            flash[:notice] = 'パスワードとパスワード確認が一致しません'
            #render 'new'
            redirect_to '/'
        end
    end
    def destroy
        b = User.find(params[:id])
        b.destroy
        redirect_to root_path
    end
  
    def show
        @users = User.find(params[:id])
    end
  
    
  
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/aiueo.html.erb
<h2>ログイン中です</h2>
<p> <%= link_to '新規ツイート' , new_tweet_path %> </p>
<p><%= link_to "ログアウト",top_logout_path %></p>
<p> <%= link_to 'ユーザー一覧', users_path%>


<% @tweets.each do |a| %>
    <% flg = 0 %>
    <p>
        [メッセージ]
        <%= a.message %>
        
        [ログインid]
        <% begin %>
            <%= User.find(a.user_id).uid %>
            
        <% rescue %>
            IDは削除されました
        <% end %>
        
        <% begin %><!-- 誰もいいねしていない場合errorが出るのを回避 -->
        <!-- u:良いねしているユーザ --->
        <!-- array:良いねしているユーザの配列 --->
            <% array=[] %>
            <% u = @likes.where(tweet_id: a.id) %>
            <% u.each do |u2| %>
                <%= u2 %>
                <% array.push(User.find(u2.user_id).uid) %>
            <!-- もしいいねしていたらflg true --->
                <% if User.find(u2.user_id).uid == session[:login_uid] %>
                    <% flg = 1 %>
                <% end %>
            <% end %>
        
        <% rescue %>
            <% u = 404 %>
        <% end %>
        <%= flg %>
        <% if flg == 1 %>
            <%= link_to 'いいね削除', like_path(a), method: :delete %>
        <% else %>
            <%= link_to 'いいね', likes_path(tweet_id: a.id), method: :post %>
        <% end %>
        
        <%= link_to '削除', "/tweets/#{a.id}", method: :delete %>
        
        
        
        
    </p>
    
<% end %>
<%= "ログインID: " + session[:login_uid] + "さん" %>

app/views/top/error.html.erb
エラー
<%= link_to'戻る', :back %>

app/views/top/login.html.erb
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<h2>ログインしてください</h2>
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>
<p><%= link_to "ユーザー一覧","/top/rock" %></p>
<p><%= link_to 'アカウント作成', "/users/new" %></p>

app/views/top/main.html.erb
<h2>ログイン中です</h2>
<p> <%= link_to '新規ツイート' , new_tweet_path %> </p>
<p><%= link_to "ログアウト",top_logout_path %></p>
<p> <%= link_to 'ユーザー一覧', users_path%>


<% @tweets.each do |a| %>
    <% flg = 0 %>
    <p>
        [メッセージ]
        <%= a.message %>
        
        [ログインid]
        <% begin %>
            <%= User.find(a.user_id).uid %>
            
        <% rescue %>
            IDは削除されています
        <% end %>
        
        <% begin %>
            
            <% u = @likes.where(tweet_id: a.id) %>
            <% u.each do |u2| %>
                <% if User.find(u2.user_id).uid == session[:login_uid] %>
                    <% flg = 1 %>
                <% end %>
            <% end %>
        
        <% rescue %>
            
        <% end %>
        
        <% if flg == 1 %>
            <%= link_to 'いいね削除', like_path(a), method: :delete %>
        <% else %>
            <%= link_to 'いいね', likes_path(tweet_id: a.id), method: :post %>
        <% end %>
        
        <%= link_to '削除', "/tweets/#{a.id}", method: :delete %>
        
        
        
        
    </p>
    
<% end %>
<%= "ログインID: " + current_user.uid + "さん" %>

app/views/tweets/index.html.erb
<h2> ツイート一覧 </h2>

<% @tweets.each do |a| %>
    <p>
        [メッセージ]
        <%= a.message %>
        <>
        <% if Like.where(user_id: @user, tweet_id: a.id).exists? %>
            <%= link_to 'いいね削除', like_path(a.id), method: :delete %>
        <% else %>
            <%= link_to 'いいね', likes_path(tweet_id: a.id), method: :post %>
        <% end %>

        <%= link_to '削除', "/tweets/#{a.id}", method: :delete %>
    </p>
<% end %>

<p> <%= link_to '新規ツイート' , new_tweet_path %> </p>

app/views/tweets/new.html.erb
<%= form_for @tweets , url: {action: :create} do |f| %>
<%= f.label :message, 'メッセージ' %>
<%= f.text_field :message %>

<%= f.submit 'ツイートする' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |a| %>
    <p>
        
        [ユーザID]
        <%= a.uid %>
        [パスワード]
        <%= a.pass %>
        
        <%= link_to '削除', "/users/#{a.id}", method: :delete %>
        
        
        
    </p>
<% end %>
<p><%= link_to 'アカウント作成', "/users/new" %></p>

app/views/users/new.html.erb
<%= form_for @users , url: {action: :create} do |f| %>
<%= f.label :uid, 'ユーザーID' %>
<%= f.text_field :uid %>


<%= f.label :password, 'パスワード' %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, 'パスワード(確認)' %>
<%= f.password_field :password_confirmation %>

<%= f.submit '登録' %>
<% end %>

app/views/users/rock.html.erb
<% @users.each do |a| %>
    <p>
        
        [ユーザID]
        <%= a.uid %>
        [パスワード]
        <%= a.pass %>
        
        
        
        
        
    </p>
<% end %>
<p><%= link_to 'アカウント作成', "/users/new" %></p>